basePath: /api/v1
definitions:
  common.SimpleResponse:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Hostinger HTTP service for managing IP address block lists.
  title: Hostinger Block List API
  version: "1.0"
paths:
  /block:
    post:
      consumes:
      - application/json
      description: Block an IP address
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.SimpleResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.SimpleResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.SimpleResponse'
      summary: Block an IP addresss
  /search/{address}:
    get:
      consumes:
      - application/json
      description: Search for an IP address
      parameters:
      - description: IP address to search for
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.SimpleResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.SimpleResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.SimpleResponse'
      summary: Search for an IP address
  /unblock/{address}:
    delete:
      consumes:
      - application/json
      description: Unblock an IP address
      parameters:
      - description: IP address to unblock
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.SimpleResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.SimpleResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.SimpleResponse'
      summary: Unblock an IP addresss
swagger: "2.0"
