basePath: /api/v1
definitions:
  hbl.Address:
    properties:
      action:
        type: string
      author:
        type: string
      comment:
        type: string
      createdAt:
        type: string
      ip:
        type: string
    type: object
  hbl.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Hostinger HTTP service for managing IP address block lists.
  title: Hostinger Block List API
  version: "1.0"
paths:
  /addresses:
    get:
      consumes:
      - application/json
      description: Use this endpoint to fetch details about all already blocked or
        allowed IP addresses.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/hbl.Address'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/hbl.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/hbl.Error'
      summary: Get all IP addresses.
      tags:
      - Addresses
    post:
      consumes:
      - application/json
      description: Use this endpoint to Block or Allow an IP address depending on
        Action argument in body.
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/hbl.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/hbl.Error'
      summary: Block or Allow an IP address.
      tags:
      - Addresses
  /addresses/{ip}:
    delete:
      consumes:
      - application/json
      description: Use this endpoint to delete an already blocked or allowed IP address.
      parameters:
      - description: IP Address
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/hbl.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/hbl.Error'
      summary: Delete an IP address.
      tags:
      - Addresses
    get:
      consumes:
      - application/json
      description: Use this endpoint to fetch details about an already blocked or
        allowed IP address.
      parameters:
      - description: IP Address
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hbl.Address'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/hbl.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/hbl.Error'
      summary: Get an IP address.
      tags:
      - Addresses
  /addresses/check/{name}/{ip}:
    get:
      consumes:
      - application/json
      description: Use this endpoint to fetch details about an already blocked or
        allowed IP address.
      parameters:
      - description: Name of the Checker
        in: path
        name: name
        required: true
        type: string
      - description: IP Address
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hbl.Address'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/hbl.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/hbl.Error'
      summary: Get an IP address.
      tags:
      - Addresses
swagger: "2.0"
