basePath: /api/v1
definitions:
  dnsrbl.Address:
    properties:
      address:
        type: string
      comment:
        type: string
      createdAt:
        type: string
    type: object
  dnsrbl.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Hostinger HTTP service for managing IP address block lists.
  title: Hostinger Block List API
  version: "1.0"
paths:
  /blocklist:
    get:
      consumes:
      - application/json
      description: Get all IP addresses
      parameters:
      - description: The IP address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dnsrbl.Address'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
      summary: Get all IP addresses
      tags:
      - Addresses
    post:
      consumes:
      - application/json
      description: Block an IP address
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
      summary: Block an IP addresss
      tags:
      - Addresses
  /blocklist/{address}:
    delete:
      consumes:
      - application/json
      description: Unblock an IP address
      parameters:
      - description: The IP address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
      summary: Unblock an IP addresss
      tags:
      - Addresses
    get:
      consumes:
      - application/json
      description: Get an IP address
      parameters:
      - description: The IP address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dnsrbl.Address'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dnsrbl.ErrorResponse'
      summary: Get an IP address
      tags:
      - Addresses
swagger: "2.0"
